.TH NYX-MACSPOOF 8 "June 2025" "Nyx Offensive Suite" "System Administration Utilities"
.SH NAME
nyx-macspoof \- MAC address spoofing utility from the Nyx Offensive Suite
.SH SYNOPSIS
.B nyx-macspoof
[\fB\-i\fR \fIINTERFACE\fR]
[\fB\-m\fR \fIMAC\fR]
[\fB\-r\fR]
[\fB\-s\fR]
[\fB\--restore\fR]
[\fB\-l\fR]
[\fB\-h\fR]
.SH DESCRIPTION
.B nyx-macspoof
is a tool for modifying MAC addresses on network interfaces.
It allows penetration testers to change MAC addresses to random values or specific addresses,
list available interfaces, and restore original MAC addresses when tests are complete.
.PP
This utility is part of the Nyx Offensive Suite, a modular penetration testing framework.
.SH OPTIONS
.TP
.BR \-i ", " \--interface =\fIINTERFACE\fR
Specify the network interface to operate on (e.g., eth0, wlan0).
.TP
.BR \-m ", " \--mac =\fIMAC\fR
Set a custom MAC address. Must be in the format XX:XX:XX:XX:XX:XX.
.TP
.BR \-r ", " \--random
Generate and apply a random MAC address using common vendor prefixes.
.TP
.BR \-s ", " \--show
Show the current MAC address of the specified interface.
.TP
.BR \--restore
Restore the original MAC address (if previously saved).
.TP
.BR \-l ", " \--list
List all available network interfaces and their current MAC addresses.
.TP
.BR \-h ", " \--help
Display help and usage information.
.SH EXAMPLES
.TP
List all available interfaces:
.B nyx-macspoof --list
.TP
Display current MAC address:
.B nyx-macspoof -i eth0 --show
.TP
Set a random MAC address:
.B nyx-macspoof -i eth0 --random
.TP
Set a specific MAC address:
.B nyx-macspoof -i eth0 -m 00:11:22:33:44:55
.TP
Restore original MAC address:
.B nyx-macspoof -i eth0 --restore
.SH FILES
.TP
.I ~/.nyx/macspoof_*
Saved original MAC addresses
.SH SEE ALSO
.BR ip (8),
.BR ifconfig (8),
.BR macchanger (1)
.SH BUGS
Please report bugs to: https://github.com/your-username/nyx/issues
.SH AUTHOR
Neur0sis (2025)
.SH COPYRIGHT
Copyright \(co 2025 Neur0sis
.PP
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.